/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.Vista;

import javax.swing.JFrame;

/**
 *
 * @author usuario
 */
public class VistaVentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaVentanaPrincipal
     */
    public VistaVentanaPrincipal() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);//Hacemos que esta ventana se genere en el medio de nuestra pantalla.
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);//define que cuando se puse el boton con la X en rojo, se cierre la ventana y se libere en memoria
        this.setResizable(false);//La ventana mantendrá un tamaño fijo
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBienvenida = new javax.swing.JLabel();
        jButtonDeportes = new javax.swing.JButton();
        jButtonAtletas = new javax.swing.JButton();
        jButtonJuegos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelBienvenida.setText("Bienvenido");

        jButtonDeportes.setText("Deportes");

        jButtonAtletas.setText("Atletas");

        jButtonJuegos.setText("Juegos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jButtonAtletas)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBienvenida)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonDeportes)
                        .addGap(40, 40, 40)
                        .addComponent(jButtonJuegos)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabelBienvenida)
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDeportes)
                    .addComponent(jButtonAtletas)
                    .addComponent(jButtonJuegos))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAtletas;
    public javax.swing.JButton jButtonDeportes;
    public javax.swing.JButton jButtonJuegos;
    private javax.swing.JLabel jLabelBienvenida;
    // End of variables declaration//GEN-END:variables
}
