package com.mycompany.Vista;

import com.mycompany.Modelo.AtletaDAO;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Colorado JImenez Victor
 */
public class VistaVentanaAtletas extends javax.swing.JFrame {

    AtletaDAO a1;
   

    public VistaVentanaAtletas(AtletaDAO a1) {
        initComponents();
        this.a1 = a1;
        this.setVisible(true);
        this.setLocationRelativeTo(null);//Hacemos que esta ventana se genere en el medio de nuestra pantalla.
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);//define que cuando se puse el boton con la X en rojo, se cierre la ventana y se libere en memoria
        this.setResizable(false);//La ventana mantendrá un tamaño fijo
    
        //Creamos y cargamos datos en la tabla
        cargarDatosAtletas();
    }
    
    public void cargarDatosAtletas() {
        List<String[]> atletas = a1.obtenerAtletas();  // Ahora devuelve un arreglo con id_atleta, nombre, género y altura

        // Crear el modelo de la tabla
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID Atleta");
        modelo.addColumn("Nombre Completo");
        modelo.addColumn("Género");
        modelo.addColumn("Altura");

        // Llenar la tabla con los datos
        for (String[] atleta : atletas) {
            modelo.addRow(atleta);
        }

        // Asignar el modelo de la tabla a jTableAtletas
        jTableAtletas.setModel(modelo);
    }

    // Método para filtrar los datos en la tabla según el texto de búsqueda
    public void filtrarTabla(String busqueda) {
        List<String[]> atletas = a1.obtenerAtletas();
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID Atleta");
        modelo.addColumn("Nombre Completo");
        modelo.addColumn("Género");
        modelo.addColumn("Altura");

        // Filtramos los datos según la búsqueda
        for (String[] atleta : atletas) {
            if (atleta[1].toLowerCase().contains(busqueda.toLowerCase())) {  // Buscamos solo en el nombre
                modelo.addRow(atleta);
            }
        }

        // Asignar el modelo de la tabla filtrada
        jTableAtletas.setModel(modelo);
    }

    // Método para obtener el atleta seleccionado de la tabla
    public String[] getAtletaSeleccionado() {
        int filaSeleccionada = jTableAtletas.getSelectedRow();
        if (filaSeleccionada != -1) {
            String id = (String) jTableAtletas.getValueAt(filaSeleccionada, 0);
            String nombre = (String) jTableAtletas.getValueAt(filaSeleccionada, 1);
            String genero = (String) jTableAtletas.getValueAt(filaSeleccionada, 2);
            String altura = (String) jTableAtletas.getValueAt(filaSeleccionada, 3);
            return new String[]{id, nombre, genero, altura};  // Devolvemos el id junto con los otros datos
        }
        return null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAtletas = new javax.swing.JTable();
        jTextFieldAtletas = new javax.swing.JTextField();
        jButtonBuscarAtletas = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableAtletas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableAtletas);

        jButtonBuscarAtletas.setText("Buscar");

        jButtonAtras.setText("Atrás");
        jButtonAtras.setActionCommand("Atras");

        jButtonEditar.setText("Editar");

        jButtonRegistrar.setText("Registrar");

        jButtonEliminar.setText("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldAtletas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonBuscarAtletas)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAtras)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAtletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarAtletas)
                    .addComponent(jButtonAtras)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonRegistrar)
                    .addComponent(jButtonEliminar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAtras;
    public javax.swing.JButton jButtonBuscarAtletas;
    public javax.swing.JButton jButtonEditar;
    public javax.swing.JButton jButtonEliminar;
    public javax.swing.JButton jButtonRegistrar;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableAtletas;
    public javax.swing.JTextField jTextFieldAtletas;
    // End of variables declaration//GEN-END:variables
}
