package com.mycompany.Vista;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author usuario
 */
public class VistaVentanaPrincipal extends javax.swing.JFrame {

    private JLabel jLabelFondo;

    /**
     * Creates new form VistaVentanaPrincipal
     */
    public VistaVentanaPrincipal() {
        this.setSize(1200, 700); // Cambiar tamaño de la ventana
        this.setLayout(null);    // Usar un layout absoluto
        initComponents();
        setFondo();              // Llamar a setFondo aquí
        this.setVisible(true);
        this.setLocationRelativeTo(null); // Ventana centrada en pantalla
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Liberar memoria al cerrar
        this.setResizable(false); // Evitar redimensionado
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        // Crear fondo
        jLabelFondo = new JLabel();
        setFondo();

        // Inicializar componentes
        jLabelBienvenida = new JLabel("Bienvenido");
        jLabelBienvenida.setFont(new Font("Arial", Font.BOLD, 48));
        jLabelBienvenida.setForeground(Color.WHITE);

        jButtonDeportes = new JButton();
        jButtonAtletas = new JButton();
        jButtonJuegos = new JButton();
        jButtonMedallero = new JButton();

        // Estilizar botones
        styleButton(jButtonDeportes, "Deportes");
        styleButton(jButtonAtletas, "Atletas");
        styleButton(jButtonJuegos, "Juegos");
        styleButton(jButtonMedallero, "Medallero");

        // Configuración de la ventana y fondo
        setLayout(null); // Usar un layout absoluto
        add(jLabelFondo);
        add(jLabelBienvenida);
        add(jButtonAtletas);
        add(jButtonDeportes);
        add(jButtonJuegos);
        add(jButtonMedallero);

        // Posicionar elementos
        jLabelFondo.setBounds(0, 0, this.getWidth(), this.getHeight());
        jLabelBienvenida.setBounds(400, 30, 600, 50);
        jButtonAtletas.setBounds(250, 100, 150, 50);
        jButtonDeportes.setBounds(450, 100, 150, 50);
        jButtonJuegos.setBounds(650, 100, 150, 50);
        jButtonMedallero.setBounds(850, 100, 150, 50);
    }

    /**
     * Método para configurar el fondo de jLabelFondo.
     */
    private void setFondo() {
        try {
            // Cargar la imagen original
            ImageIcon originalIcon = new ImageIcon(getClass().getResource("/Logo.png"));
            
            // Escalar la imagen al tamaño de la ventana
            Image scaledImage = originalIcon.getImage().getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_SMOOTH);
            
            // Crear un nuevo ImageIcon con la imagen escalada
            ImageIcon scaledIcon = new ImageIcon(scaledImage);
            
            // Asignar el icono al JLabel
            jLabelFondo.setIcon(scaledIcon);
            
            // Asegurar que el JLabel esté detrás de otros componentes
            this.getLayeredPane().setLayer(jLabelFondo, Integer.MIN_VALUE);
            
            // Configurar el tamaño y posición del JLabel
            jLabelFondo.setBounds(0, 0, this.getWidth(), this.getHeight());
        } catch (Exception e) {
            System.err.println("Error al cargar la imagen de fondo: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    

    // Método para aplicar el estilo a los botones
    private void styleButton(JButton button, String text) {
        button.setText(text);
        button.setFont(new Font("Arial", Font.BOLD, 20)); // Estilo y tamaño de letra
        button.setBackground(Color.BLACK); // Fondo negro
        button.setForeground(Color.WHITE); // Texto blanco
        button.setFocusPainted(false); // Eliminar el borde de selección del botón
        button.setBorderPainted(false); // Eliminar borde del botón
    }

    /**
     * Variables declaration
     */
    public javax.swing.JButton jButtonAtletas;
    public javax.swing.JButton jButtonDeportes;
    public javax.swing.JButton jButtonJuegos;
    public javax.swing.JButton jButtonMedallero;
    private javax.swing.JLabel jLabelBienvenida;
    // End of variables declaration
}
